version: "2.4"

services:
  postgres:
    build: .
    container_name: postgres13
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgsql_data
        target: /var/lib/postgresql/data

volumes:
  pgsql_data:
